### ISSUE TITLE
feature/signup-screen-logic

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#10]
### Actividades específicas:
- Conectar la pantalla de registro a la capa de dominio y datos.
- Crear un caso de uso en la capa de dominio: RegisterUserUseCase.
- Manejar estados de carga y errores (por ejemplo, "El correo ya está en uso").
- Si el registro es exitoso, guardar datos adicionales del usuario (como tipo de usuario) en Firestore.

### Criterios de aceptación:
- Los usuarios se pueden registrar con éxito.
- Los datos del usuario se almacenan en Firebase Authentication y Firestore.

**Comment by AlanMartell14** [comment]
La integración de la pantalla de registro con la capa de dominio y datos, junto con la creación del caso de uso RegisterUserUseCase, ha garantizado una arquitectura bien estructurada y modular. Además, el manejo eficaz de estados de carga y errores, como la detección de correos duplicados, asegura una experiencia de usuario fluida y sin interrupciones.

El sistema no solo permite registrar usuarios exitosamente, sino que también almacena de manera precisa los datos adicionales (como el tipo de usuario) tanto en Firebase Authentication como en Firestore.
