### ISSUE TITLE
test/auth-unit-tests

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#11]
### Actividades específicas:
- Escribir pruebas unitarias para las funciones del `AuthRepository`:
        - Prueba para inicio de sesión con credenciales correctas.
        - Prueba para manejo de errores (credenciales incorrectas, correo no registrado).
- Crear pruebas de integración para validar que el flujo de autenticación completo funciona correctamente.

### Criterios de aceptación:
- Todas las pruebas unitarias y de integración pasan exitosamente.
- Las pruebas cubren los principales escenarios de autenticación.

**Comment by AlanMartell14** [comment]
La implementación de pruebas para validar los métodos de autenticación e integración con Firebase ha generado resultados sobresalientes. Las pruebas unitarias en el AuthRepository han garantizado la fiabilidad del inicio de sesión, manejando tanto credenciales válidas como escenarios de error (credenciales incorrectas o correos no registrados) con precisión.
