### ISSUE TITLE
feature/qr-scan-setup

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#13]
**Descripción:** Configurar un paquete de Flutter para implementar el escaneo de códigos QR.
**Actividades específicas:**
  - Investigar y seleccionar el paquete más adecuado para escaneo de QR (por ejemplo, `qr_code_scanner` o `mobile_scanner`).
  - Agregar el paquete al archivo `pubspec.yaml`.
  - Configurar los permisos necesarios en Android y iOS (cámara).
  - Crear una clase base para gestionar el escaneo.

**Criterios de aceptación:**
  - El paquete de escaneo QR está configurado correctamente y probado en un dispositivo físico.
  - La cámara se activa y escanea códigos QR sin errores.

**Comment by erickmerchant05** [comment]
Actividades realizadas:
Selección e integración del paquete:

Se integró el paquete qr_code_scanner en el archivo pubspec.yaml del proyecto.
Configuración de permisos:

En Android: Se añadieron los permisos de cámara en el archivo AndroidManifest.xml.
En iOS: Se configuraron las claves necesarias en el archivo Info.plist para permitir el acceso a la cámara.
Clase base para el escaneo:

Se creó una clase base que utiliza qr_code_scanner para inicializar la cámara y procesar los datos escaneados.
Incluye callbacks para manejar resultados exitosos y posibles errores.
Pruebas en dispositivo físico:

✅ Verificado el funcionamiento en un dispositivo físico.
La cámara se activa correctamente y escanea códigos QR sin problemas.
Resultados:
El paquete está configurado correctamente.
La funcionalidad de escaneo de QR está operativa y lista para integrarse con el flujo del proyecto.
![image](https://github.com/user-attachments/assets/c9ce26e6-3fbd-4e3c-8f11-b26487db844b)

**Comment by erickmerchant05** [comment]
![image](https://github.com/user-attachments/assets/513e03cf-d4f1-4de2-9ce2-d31c01202a8f)
