### ISSUE TITLE
test/qr-scan-tests

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#16]
**Descripción:** Crear pruebas unitarias y de integración para validar la funcionalidad de escaneo de QR.
**Actividades específicas:**
  - Escribir pruebas unitarias para `ValidateQRCodeUseCase`:
    - Prueba con QR válido.
    - Prueba con QR inválido.
  - Realizar pruebas de integración para validar la interacción entre el escaneo y la validación.

**Criterios de aceptación:**
  - Las pruebas unitarias y de integración cubren los principales escenarios.
  - Todas las pruebas pasan exitosamente.

**Comment by erickmerchant05** [comment]
He completado las pruebas unitarias y de integración para la funcionalidad de escaneo de códigos QR. Las pruebas unitarias cubren los siguientes escenarios:

Código QR válido: Verifica que el sistema procesa correctamente un código QR válido.
Código QR no válido: Asegura que el sistema maneja adecuadamente un código QR no válido.
Además, se han realizado pruebas de integración para validar la interacción entre el proceso de escaneo y la validación del código QR. Todas las pruebas han pasado exitosamente, cumpliendo con los criterios de aceptación establecidos.
![image](https://github.com/user-attachments/assets/455f572f-a02f-4399-b6da-4fa093eac2fe)
QR generado en formato JSON
Para ser Escaneado por medio de la camara y dar la respuesta de la VISITA 8
![image](https://github.com/user-attachments/assets/ef3c7153-a679-4d86-9eaf-10dd489659f3)
