### ISSUE TITLE
test/full-flow-tests

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#23]
**Descripción:** Realizar pruebas end-to-end que validen el flujo completo de la aplicación.

**Actividades específicas:**

  - Simular el escaneo de un QR y verificar que el registro de la visita se realice correctamente en la base de datos.
  - Verificar que el flujo de navegación entre las pantallas (escaneo, resultados, registro manual) funcione sin interrupciones.
  - Probar la entrada manual de un usuario y verificar que se registre correctamente.

**Criterios de aceptación:**

  - El flujo completo (escaneo y registro manual) funciona sin errores.
  - Los registros se reflejan correctamente en la base de datos y en la pantalla de resultados.

**Comment by AlanMartell14** [comment]
La implementación y pruebas del flujo de escaneo y registro manual han demostrado resultados altamente exitosos, cumpliendo con los estándares establecidos. La simulación del escaneo de códigos QR verificó que cada visita se registre correctamente en la base de datos, mientras que las pruebas del flujo de navegación confirmaron una transición fluida e ininterrumpida entre las pantallas de escaneo, resultados y registro manual.
