### ISSUE TITLE
feature/firebase-setup

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#3]
### Actividades específicas:

- Crear un proyecto en Firebase Console llamado ` Control Access App`.
- Habilitar los siguientes servicios en Firebase:
    - Firebase Authentication.
    - Cloud Firestore.
- Descargar el archivo ` google-services.json` (para Android) y ` GoogleService-Info.plist` (para iOS).
- Agregar los archivos descargados al proyecto Flutter en las carpetas correspondientes (`android/app` y `ios/Runner`).
- Configurar `Firebase.initializeApp()` en el archivo principal de Flutter (`main.dart`).

### Criterios de aceptación:
- Firebase está correctamente configurado en Android e iOS.
- La inicialización de Firebase funciona sin errores.

**Comment by AlanMartell14** [comment]
El proyecto Control Access App se configuró exitosamente en Firebase, cumpliendo con todos los estándares establecidos. La habilitación de servicios clave como Firebase Authentication y Cloud Firestore proporcionó la base necesaria para implementar funcionalidades de autenticación y almacenamiento de datos en tiempo real.

Los archivos descargados (google-services.json y GoogleService-Info.plist) se integraron correctamente en las carpetas correspondientes de Android e iOS, y la configuración de Firebase.initializeApp() en el archivo principal de Flutter (main.dart) se completó sin contratiempos.
