### ISSUE TITLE
feature/firebase-auth-setup

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#6]
### Actividades específicas:
- Habilitar el método de autenticación de correo y contraseña en Firebase Console.
- Crear una clase AuthRepository en la capa de datos con las siguientes funciones:
   - `signIn(email, password)`
   - `signUp(email, password)`
   - `signOut()`
   - `getCurrentUser()`
- Manejar errores comunes como usuario no encontrado o contraseña incorrecta.
- Documentar los métodos creados.

### Criterios de aceptación:
- Los métodos de autenticación están implementados y documentados.
- Firebase Authentication está configurado y funciona correctamente.

**Comment by AlanMartell14** [comment]
La implementación de los estándares para la configuración e integración de Firebase Authentication ha sido un éxito rotundo. Habilitar el método de autenticación por correo y contraseña en Firebase Console y desarrollar la clase AuthRepository con funciones clave (signIn, signUp, signOut y getCurrentUser) permitió crear un sistema robusto y funcional para gestionar la autenticación de usuarios.
