### ISSUE TITLE
feature/login-screen-ui

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#7]
### Actividades específicas:
- Diseñar una interfaz atractiva y funcional utilizando widgets de Flutter.
- Elementos básicos de la pantalla:
   - Campos de texto para correo y contraseña.
   - Botón de "Iniciar sesión".
   - Indicador de carga mientras se procesa la solicitud.
   - Mensajes de error en caso de credenciales inválidas.
- Agregar navegación hacia otras pantallas después del inicio de sesión exitoso.

### Criterios de aceptación:
- La pantalla de inicio de sesión tiene un diseño claro y funcional.
- Los usuarios pueden interactuar con la interfaz sin problemas.

**Comment by erickmerchant05** [comment]
La pantalla de inicio de sesión para Administradores y Usuarios ya se encuentra lista y funcional.

Detalles implementados:

	1.	Interfaz atractiva y funcional:
	•	Se utilizó un diseño limpio y moderno, optimizado para dispositivos móviles y web.
	•	Los campos de texto para correo y contraseña están claramente etiquetados, con validación básica incorporada.
	2.	Funcionalidad básica:
	•	Botón de “Iniciar sesión” correctamente configurado para validar los datos.
	•	Indicador de carga implementado para mostrar retroalimentación mientras se procesa la solicitud.
	•	Mensajes de error dinámicos añadidos para informar al usuario en caso de credenciales inválidas.
	3.	Navegación:
	•	Redirección configurada hacia las pantallas de Administrador y Usuario según las credenciales proporcionadas.

Criterios de aceptación cumplidos:

	•	Diseño claro y funcional: La pantalla es fácil de usar y sigue las mejores prácticas de UX/UI.
	•	Interactividad: La validación y retroalimentación funcionan como se esperaba, brindando una experiencia fluida.

El desarrollo está completo y listo para su revisión o integración con el backend.
![image](https://github.com/user-attachments/assets/e707b4ef-c160-4527-b1b5-3473ff9c31fe)
