### ISSUE TITLE
feature/signup-screen-ui

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/control_access_app#9]
### Actividades específicas:
- Diseñar una interfaz con los siguientes elementos:
    - Campos de texto para nombre, correo y contraseña.
    - Botón "Registrarse".
    - Opcional: Selector para determinar el tipo de usuario (Administrador o Usuario).
- Validar los campos de entrada antes de enviar los datos a Firebase.

### Criterios de aceptación:
- La pantalla de registro tiene un diseño claro y funcional.
- Los datos se validan correctamente antes de intentar el registro.

**Comment by erickmerchant05** [comment]
Actividades realizadas:
Diseño de la interfaz:

Se creó una pantalla con los siguientes elementos:
Campos de texto:
Nombre.
Apellido.
Correo electrónico.
Botón "Registrarse": Bien posicionado para una experiencia de usuario fluida.
Validación de campos:

Validaciones implementadas:
Nombre y apellido: No pueden estar vacíos.
Correo: Validación de formato adecuado.
Mensajes de error visibles si el usuario deja campos vacíos o introduce un correo no válido.
Pruebas realizadas:

Probado con datos válidos para confirmar que el registro funciona correctamente.
Verificado que los mensajes de error aparezcan ante datos incompletos o incorrectos.
Resultados:
La pantalla tiene un diseño funcional y amigable.
Los datos se validan correctamente antes de proceder al registro.
![image](https://github.com/user-attachments/assets/690573a5-a137-441c-9287-205f50a2d40e)
![image](https://github.com/user-attachments/assets/55ea5034-1b99-44fa-b8ab-1d7220c6fd95)
